name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload to Hugging Face Space
      uses: huggingface/hub-actions@v1
      with:
        repo-id: ${{ secrets.HF_SPACE_ID }}
        repo-type: space
        token: ${{ secrets.HF_TOKEN }}
